### ISSUE TITLE
请教：比如2个页签都keep-alive, 然后关闭了当前的页签，如何刷新另外一个页签【不想缓存了】

### ISSUE THREAD

**Issue by tianyazjq** [yunsii/use-switch-tabs#1]
请教：比如2个页签都keep-alive,然后关闭了当前的页签，history.push('另外一个页签')，这个页签因为有些时候特殊业务，我想要刷新一下页面,就是不加keep-alive的效果。这个要什么弄啊

**Comment by tianyazjq** [comment]
![image](https://user-images.githubusercontent.com/5754329/136647344-62b8bf51-6b06-43fa-a515-2f00e78f5eff.png)
关闭了，另外一个页签我想刷新一下，触发useEffect一下，就是没有keep-alive之前的样子。

**Comment by yunsii** [comment]
抱歉，没太看懂你说的意思，简单理解是在关闭一个 tab 的时候需要刷新另一个 tab？如果是这样的话，`reloadTab` 支持入参的，可以看看 https://github.com/theprimone/use-switch-tabs/blob/master/src/useSwitchTabs.ts#L49 或许能够满足需求。

**Comment by tianyazjq** [comment]
谢谢大佬，已经解决了，用reloadTab就可以了。
![image](https://user-images.githubusercontent.com/5754329/136739051-1132ebc4-2575-4bce-b5b9-fa5352708537.png)
