### ISSUE TITLE
怎么统一给每个路由的组件添加withSwitchTab

### ISSUE THREAD

**Issue by wmb0412** [yunsii/use-switch-tabs#10]
谢谢大佬的开源， 问一个可能和组件库没有关系的问题。
tab太多的时候会卡，有办法再统一的地方一起添加withSwitchTab吗，而不是再每个组件中单独的添加withSwitchTab，因为有点麻烦又怕后期会修改

**Comment by yunsii** [comment]
如果不想手动添加的话，不是很确定直接在 https://github.com/yunsii/use-switch-tabs/blob/3e2872a937ae79ab671ce1fc94c7885824b362d1/src/useSwitchTabs.ts#L396 套上 withSwitchTab 好不好使，你有空可以测试下，好用的话可以 PR 一下 😂

**Comment by wmb0412** [comment]
> 如果不想手动添加的话，不是很确定直接在
> 
> https://github.com/yunsii/use-switch-tabs/blob/3e2872a937ae79ab671ce1fc94c7885824b362d1/src/useSwitchTabs.ts#L396
> 
> 套上 withSwitchTab 好不好使，你有空可以测试下，好用的话可以 PR 一下 😂

我的react水平不高， 我之前看过您的代码知道可能是在这里加，但是我不是怎么改变这个children😂
```js
content: withSwitchTab(children)
```
我试了这样子不行， 知道因为children是react element，withSwitchTab需要的参数是react component ，但是我不知道怎么修改

**Comment by yunsii** [comment]
哦对，本身这个 HOC 是针对 React.ComponentType 的，也就是 React.createElement 的入参之一，chidlren 已经是 React.createElement 的返回结果了，那显然是不行的。这样子看起来还是只能在页面代码入口添加了，不想手动添加的话大概得整个插件自动添加了，那样显然成本太高了。

现在可以试试统一封装一个 Page 创建的函数，在内部统一调用 withSwitchTab，不然只能手动添加了。
