### ISSUE TITLE
pro5中怎么固定到头部并且关闭动画

### ISSUE THREAD

**Issue by aadog** [yunsii/use-switch-tabs#2]
pro5中怎么固定到头部并且关闭动画

**Comment by yunsii** [comment]
是指的 Tabs 的标签部分固定吧？内容部分设置固定高度，通过 CSS calc 减去 header 和 Tabs 标签部分相关高度就行了。Tabs 动画效果由 Tabs 组件的 `animated` 属性控制。

**Comment by yunsii** [comment]
Close as stale.
