### ISSUE TITLE
我想动态更改标签栏的标题，我该怎么做呢？

### ISSUE THREAD

**Issue by Xyn19961118** [yunsii/use-switch-tabs#4]
我这边遇到一个需求，编辑详情页的时候要将标签栏的标题改成当前的标题，但是我这边看文档并不知道怎么做？是否有api去解决这个问题呢

**Comment by yunsii** [comment]
啊这，目前只是针对 Mode.Dynamic 支持 setTabName 的回调，这种业务能给个具体的例子吗？

**Comment by Xyn19961118** [comment]
> 啊这，针对只是针对Mode.Dynamic支持setTabName的看似，这种业务可以个个具体的例子吗？

比如在商品列表页的时候，可能会打开多个商品编辑页面，就是想把 tabName的“商品编辑”变成对应的商品名称

**Comment by yunsii** [comment]
那你这个不就是需要使用 Mode.Dynamic 模式吗？支持一个路由多开页面，然后结合 setTabName 就好了。

**Comment by yunsii** [comment]
close as stale.
