### ISSUE TITLE
怎么清除全部标签？

### ISSUE THREAD

**Issue by jsxiaosi** [yunsii/use-switch-tabs#6]
你好！我有一个应用场景是退出登录的时候清除所有标签页，如何在退出登录的时候关闭所有标签并取消缓存？

**Comment by yunsii** [comment]
根据这个[副作用](https://github.com/yunsii/use-switch-tabs/blob/master/src/useSwitchTabs.ts#L334)来看，目前应该可以通过设置 persistent 为 false 来临时解决，后续尝试将状态更新函数直接暴露出去。

**Comment by jsxiaosi** [comment]
> 根据这个[副作用](https://github.com/yunsii/use-switch-tabs/blob/master/src/useSwitchTabs.ts#L334)来看，目前应该可以通过设置 persistent 为 false 来临时解决，后续尝试将状态更新函数直接暴露出去。

persistent设置为false暂时可以满足需求！
但是，
重新登陆之后父级路由没有component标签页也会添加一个记录，这个有什么方式可以避免吗？

**Comment by yunsii** [comment]
这个建议给个重现比较好，可以 fork 在 example 里给个例子？

**Comment by jsxiaosi** [comment]
> example

就是在浏览器上输入父级的path标签也会记录
一般父级导航是不需要component直接会打开子路由的path，但是标签哪里还是会记录上父级的path

**Comment by yunsii** [comment]
这是没有为父级路由配置重定向吧，加个重定向试试？像这样：https://github.com/yunsii/use-switch-tabs/blob/master/example/config/routes.ts#L83

**Comment by jsxiaosi** [comment]
> https://github.com/yunsii/use-switch-tabs/blob/master/example/config/routes.ts#L83

这个方式不可行，因为我们的路由是有权限判断的

而且我尝试添加重定向之后其实还是会在标签上添加记录

**Comment by yunsii** [comment]
那就不该停留在父级没有 component 的路由下了，看起来你这个不是进入到页面做权限判断而是在最外层就做好了？

**Comment by jsxiaosi** [comment]
> 那就不该停留在父级没有 component 的路由下了，看起来你这个不是进入到页面做权限判断而是在最外层就做好了？

是的，似乎好像只能手动清楚父级的path，但是这样的话会吃很多的性能

**Comment by yunsii** [comment]
是自己实现的权限逻辑吗？按我的理解应该把菜单路由根据权限过滤好就不会出现这种情况了。
