### ISSUE TITLE
缓存页面是否有进入前台的生命周期？

### ISSUE THREAD

**Issue by jsxiaosi** [yunsii/use-switch-tabs#8]
缓存页面是否有进入前台的生命周期？
或者
缓存的页面进入到前台时如何做一些自定义处理

**Comment by yunsii** [comment]
缓存了就不会再触发 onMount 这样的生命周期了，可以用 `listenActiveChange` 试试，之前有过一个简单的讨论：https://github.com/yunsii/ant-design-pro-plus/issues/39

**Comment by yunsii** [comment]
Close as stale.
