### ISSUE TITLE
在antd pro v5.2.0版本里如何使用此插件？

### ISSUE THREAD

**Issue by pxim** [yunsii/use-switch-tabs#9]
看了这个example，里面结构和antd pro v5.2.0版本里结构，相差很大，不知道该如何使用此插件，

**Comment by yunsii** [comment]
之前在 https://github.com/yunsii/ant-design-pro-plus 适配过一次 ant design pro v5，5.2 的话应该也没啥问题吧，你可以看看。

**Comment by yunsii** [comment]
Close as stale.
